apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-spring-boot-api
spec:
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: spring-boot-api
                port:
                  number: 8080
          - path: /logs
            pathType: Prefix
            backend:
              service:
                name: spring-boot-api
                port:
                  number: 8081
          - path: /soap
            pathType: Prefix
            backend:
              service:
                name: spring-boot-api
                port:
                  number: 8082
